return "REWARDFUN Chandler NEWTROLL KITT_RESET Sub2CaptainMaui
        DEVSCOOKING kittgaming Sub2Fer999 Enyu_is_Pro Magicbus
        JCWK Starcodeheo Bluxxy fudd10_v2 SUB2GAMERROBOT_EXP1
        Sub2NoobMaster123 Sub2UncleKizaru Sub2Daigrock Axiore
        TantaiGaming StrawHatMaine Sub2OfficialNoobie Fudd10
        Bignews TheGreatAce DRAGONABUSE SECRET_ADMIN ADMIN_TROLL
        STAFFBATTLE ADMIN_STRENGTH JULYUPDATE_RESET NOOB_REFUND
        15B_BESTBROTHERS CINCODEMAYO_BOOST ADMINGIVEAWAY
        GAMER_ROBOT_1M SUBGAMERROBOT_RESET SUB2GAMERROBOT_RESET1
        GAMERROBOT_YT TY_FOR_WATCHING EXP_5B RESET_5B UPD16
        3BVISITS 2BILLION UPD15 THIRDSEA 1MLIKES_RESET UPD14
        1BILLION ShutDownFix2 XmasExp XmasReset Update11
        PointsReset Update10 Control SUB2OFFICIALNOOBIE AXIORE
        BIGNEWS BLUXXY CHANDLER ENYU_IS_PRO FUDD10 FUDD10_V2
        KITTGAMING MAGICBUS STARCODEHEO STRAWHATMAINE
        SUB2CAPTAINMAUI SUB2DAIGROCK SUB2FER999 SUB2NOOBMASTER123
        SUB2UNCLEKIZARU TANTAIGAMING THEGREATACE CONTROL UPDATE11
        XMASEXP Colosseum"
